# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9fc12aad36db003b09c5c07d0fd226e56e4a6976d5eccdbf14dd9074ebd22f772eaf59a2e366e49e250ff1e04b96c2f6ce1db215ce6113326be900e1d78c590c

test:
  secret_key_base: 514c654d1c1fa39d86b77ca1645a9e066ee30324a4bdaf7cc46fabc15e271488dc428e2c9ed04c5375a0ef5a0baccc17caf052b601d144141a718f009948f2b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
